### ISSUE TITLE
[Feature Request] 添加对array格式上报的支持

### ISSUE THREAD

**Issue by wdvxdr1123** [ColdThunder11/forward_ad_killer#2]
在目前版本下，go-cqhttp端配置了 `post_message_format: array`时，插件无法生效

**Comment by ColdThunder11** [comment]
> 在目前版本下，go-cqhttp端配置了 `post_message_format: array`时，插件无法生效

已经支持了，话说有没有计划给gocq支持嵌套转发消息的解析
